baseURL = "https://lisette-subset.github.io/technical-journal/"
title = "Lisette's Technical Journal"
theme = "hugo-book"
languageCode = "en-us"
enableGitInfo = true

# (Optional but handy)
[params]
  BookTheme = "auto"       # light/dark auto
  BookToC = true           # show table of contents
  BookSearch = true        # built-in search
  BookRepo = "https://lisette-subset.github.io/technical-journal/"

# Recommended for clean code blocks
[markup]
  [markup.highlight]
    noClasses = false
